### ISSUE TITLE
Authoring tool: final to-do list

### ISSUE THREAD

**Issue by mtongen** [artsmia/griot#15]
- [x] Goldweights - final content outline ready
- [x] Need list of 9 videos to feature on home screen
- [x] Enter all video links (with thumbnails)
- [x] Confirm image credits from metadata
- [x] Finalize tombstone data for all objects - list from NT?
- [x] Check for errors related to pasting from Word (special characters)
