### ISSUE TITLE
Remaining functionality checklist

### ISSUE THREAD

**Issue by kjell** [artsmia/griot#7]
- [ ] Attract/Home Screen (#9)
#### Global
- [x] Design home button
- [x] Remove Menu Button
- [x] Design back button
- [x] Add optional caption for all media
- [ ] Add sharing function to all objects and stories
- [x] Add text enlargement function (consensus: bump font size everywhere?)
- [x] Full screen image overlay
- [x] Full screen video player
#### About
- [x] Tombstone and about text (pending updates from this morning's meeting)
#### Details
- [x] Scroll column for annotations
- [ ] Address new way of object paging
- [x] Remove View option (we weren't sure about this, after this morning's meeting it's gone)
- [ ] ?? Add different views to annotations only (I'm not sure what this refers to a week later)
- [x] Finalize detail highlighting treatment (dark transparent layer surrounds detail)
- [x] Fix zooming off screen issue
- [x] ~~Add widen and narrow text column function~~ (We decided against this)
- [x] Address design of column adjustment button
#### Stories
- [x] Story paging functionality
- [x] Related object functionality
- [x] Video only template
- [x] Landscape image template
- [x] Portrait image template
- [x] Side-by-side comparison template
- [x] Bibliography reference page
#### Other/Technical
- [x] Image, audio/video caching
- [x] Timeout
- [x] WiFi testing
- [x] Forced Refresh
- [x] Analytics
